### ISSUE TITLE
FAILURE TO OPEN SYMBEAM 

### ISSUE THREAD

**Issue by javi223** [amcc1996/symbeam#10]
Hello, I am trying to install symbeam on my laptop, I have a windows system and it didnt work, after installing a linux subsystem is didnt work either, this is the code that shows up for the failure:

Building wheels for collected packages: symbeam, matplotlib
  Building wheel for symbeam (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      /usr/lib/python3.10/distutils/dist.py:259: UserWarning: 'licence' distribution option is deprecated; use 'license'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      error: could not create 'build': Permission denied
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for symbeam
  Running setup.py clean for symbeam
  Building wheel for matplotlib (setup.py) ... |

Anyone sure why that is?

**Comment by amcc1996** [comment]
Hi @javi223 ! I will try to look into this this week. Can you please give some more information about your system setup?
- What Linux subsystem are you using?
- Do you have other Python packages installed and working properly?
- Do you have administrator access to your system?

**Comment by javi223** [comment]
> Hi @javi223 ! I will try to look into this this week. Can you please give some more information about your system setup?
> 
> * What Linux subsystem are you using?
> * Do you have other Python packages installed and working properly?
> * Do you have administrator access to your system?

Thank you, I have already solved the issue! The only issue right now is that my beam is statically indeterminate, but I will try and sort that out, thank you anyways!
