### ISSUE TITLE
Get data points from analysis

### ISSUE THREAD

**Issue by KiloDeltaApps** [amcc1996/symbeam#8]
Is it possible to get data points from the analysis? So output the shear force and bending at a certain x. Cannot find it in the documentation.

**Comment by amcc1996** [comment]
I believe there is no designed feature to do that. The data structures do exist but are somewhat hidden from the user. You can access the list of `segments` and each segment contains the `shear_force` and `bending_moment` among others. For instance, in example 1:
```python
import matplotlib.pyplot as plt

from symbeam import beam


test_beam = beam("l", x0=0)
test_beam.add_support(0, "roller")
test_beam.add_support("l", "pin")
test_beam.add_distributed_load(0, "l/2", "-2 * q / l * x")
test_beam.add_distributed_load("l/2", "l", "-q")
test_beam.solve()
fig, ax = test_beam.plot()

plt.savefig(__file__.split(".py")[0] + ".svg")

# Accessing the symbolic expressions of the shear force and bending moment
print(test_beam.segments[0].shear_force)
print(test_beam.segments[0].bending_moment)

# Evaluate in the target point, x0
x0 = 1.0
print(test_beam.segments[0].shear_force.subs({'x': x0}))
print(test_beam.segments[0].bending_moment.subs({'x': x0}))
```

In the future, one could add new functions, `evaluate_shear_force(x)` and `evaluate_bending_moment` to retrieve this information more easily.

**Comment by amcc1996** [comment]
@Juulpy if this suffices for you at this moment, it will be fine for me. Otherwise, I can create a new release with the new feature.

**Comment by amcc1996** [comment]
Since the code allows doing what has been initially proposed in the issue, and a possible solution has been demonstrated, I will consider this issue closed.
