### ISSUE TITLE
Hyper-static beams

### ISSUE THREAD

**Issue by miguelmaso** [amcc1996/symbeam#9]
Hi, googling a little I've just found this repo. Nice job!
I would like to ask if it's planned to extend this repo to hyper-static beams. It would be very useful for didactical purpose.
Thanks in advance

```
RuntimeError: The number of equilibirum equations is less than the number of fixed degrees of freedom: the beam is statically indeterminate.
```

**Comment by amcc1996** [comment]
Hello! Thanks for the support, I appreciate it!
Honestly, `symbeam` was not designed to solve hyper-static beams and it is not really in the plans to extend it, at this moment.

Anyway, I recommend you the package [IndeterminateBeam](https://github.com/JesseBonanno/IndeterminateBeam) which can deal with hyper-static beams and might help you out on your task!

**Comment by miguelmaso** [comment]
Hello, thanks for the hint, the package indeterminatebeam will be helpful
